version: Compose specification
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: example
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD", "psql", "-U", "admin", "-d", "example", "-c", "SELECT 1"]
            interval: 5s
            timeout: 5s
            retries: 5
